<span id="toTop" style="display: none;"><span><i class="icon-angle-up"></i></span></span>

<!--  javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/themes/js/jquery-1.8.3.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/themes/js/smart.js"></script>
<script src="/themes/js/my.js"></script>
<?php echo $this->inlineScript(); ?>
</body>
</html>