<!-- Facebook script -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<header class="header">
    <h1 class="seo">Seja bem vindo e anuncie concosco gratuitamente! - Para destaque na primeira página por favor opte pela opção de destaque.</h1>
    <div class="container">
        <div class="row">
            <div class="offset6 span6 right-align loginArea">
                <a href="<?php echo $this->url('banner'); ?>" role="button" data-toggle="modal"><span class="btn btn-mini">PUBLICAR BANNER NO RODAPE</span></a>
                <a href="<?php echo $this->url('anunciar'); ?>"><span class="btn btn-mini btn-danger">ANUNCIAR</span></a>
                <!--<a href="register.php"><span class="btn btn-mini btn-success">AINDA NAO SE TORMOU MEMBRO/SAIR</span></a>-->
            </div>
        </div>
        <div class="navbar">
            <?php echo $this->partial('partial/navigation'); ?>
        </div>
    </div>
</header>