<?php echo $this->doctype();
$currentSelecteLang = "en";
?>
<html lang="en">
  <head>
     <meta charset="utf-8">
     <title>Sexo ja - Anuncie neste portal...!</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta name="description" content="sexo ja, site de anuncios para adultos.">
     <meta name="author" content="sexo ja">
     <meta name="keywords" content="Sexo,acompanhantes porto,acompanhantes lisboa,acompanhantes, sexo portugal,rua69, sexo na cama">
        <!-- styles -->
     <link rel="stylesheet/less" type="text/css" href="/themes/less/bootstrap.less">
      <link rel="stylesheet" type="text/css" href="/themes/css/mystyles.css">
     <script src="/themes/js/less/less.js" type="text/javascript"></script>
     <!-- favicon-icons -->
     <link rel="shortcut icon" href="/themes/images/favicon.ico">
  </head>
<body>
 <?php echo $this->partial('partial/google-analytics'); ?>