<?php
$serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
$searchForm = new \Application\Form\SearchForm($serviceLocator);
$searchFormUrl = $this->url('anuncios' , array( 'action' => 'index' ));
$searchForm->setAttribute('action', $searchFormUrl);
$searchForm->setAttribute('class', 'form-inline navbar-search');
?>

<div class="navbar-inner">
    <a class="brand" href="/"><img src="/themes/images/new_logo.png" alt="Sexoagora.com"></a>
    <div class="nav-collapse">
        <ul id="topMenu" class="nav pull-right">
            <li class="">
                <?php echo $this->partial('partial/search', array('searchForm' => $searchForm)); ?>
            </li>
        </ul>
    </div>
    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>