<div class="navbar-inner">
    <a class="brand" href="/"><img src="/themes/images/new_logo.png" alt="Sexoagora.com"></a>
    <div class="nav-collapse">
        <ul id="topMenu" class="nav pull-right">
            <li class="">
                <form class="form-inline navbar-search" method="post" action="/anuncios" style="padding-top:5px;">
                    <select class="span3" style="padding:11px 4px; height:auto">
                        <option value="all">Todos</option>
                        <option value="mh">Mulheres procurando Homens</option>
                        <option value="mm"> Mulheres procurando Mulheres</option>
                        <option value="hm">Homens procurando Mulheres</option>
                        <option value="hh">Homens procurando Homens</option>
                    </select>
                    <!--<input class="span4" type="text" placeholder="eg. T-shirt" style="padding:11px 4px;">-->
                    <button type="submit" class="btn btn-warning btn-large" style="margin-top:0">Ver anuncios...</button>
                </form>
            </li>
        </ul>
    </div>
    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>