<?php

namespace DoctrineORMModule\Proxy\__CG__\Anuncios\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Anuncios extends \Anuncios\Entity\Anuncios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'idAnuncio', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'titulo', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'local', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'descricao', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'permitirEmail', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'dataCriacao', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'dataExpira', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'dataEdicao', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'url', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'estado', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'tipo', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'fkCategoria', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'fkCidade', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'email', 'images');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'idAnuncio', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'titulo', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'local', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'descricao', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'permitirEmail', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'dataCriacao', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'dataExpira', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'dataEdicao', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'url', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'estado', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'tipo', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'fkCategoria', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'fkCidade', '' . "\0" . 'Anuncios\\Entity\\Anuncios' . "\0" . 'email', 'images');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Anuncios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDataCriacao($dataCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCriacao', array($dataCriacao));

        return parent::setDataCriacao($dataCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEdicao($dataEdicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEdicao', array($dataEdicao));

        return parent::setDataEdicao($dataEdicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataEdicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataEdicao', array());

        return parent::getDataEdicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataExpira($dataExpira)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataExpira', array($dataExpira));

        return parent::setDataExpira($dataExpira);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataExpira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataExpira', array());

        return parent::getDataExpira();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkCategoria($fkCategoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkCategoria', array($fkCategoria));

        return parent::setFkCategoria($fkCategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCategoria', array());

        return parent::getFkCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkCidade($fkCidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkCidade', array($fkCidade));

        return parent::setFkCidade($fkCidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCidade', array());

        return parent::getFkCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAnuncio($idAnuncio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAnuncio', array($idAnuncio));

        return parent::setIdAnuncio($idAnuncio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAnuncio()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAnuncio();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAnuncio', array());

        return parent::getIdAnuncio();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', array($local));

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', array());

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermitirEmail($permitirEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermitirEmail', array($permitirEmail));

        return parent::setPermitirEmail($permitirEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermitirEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermitirEmail', array());

        return parent::getPermitirEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Anuncios\Entity\Images $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($images));

        return parent::addImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Anuncios\Entity\Images $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($images));

        return parent::removeImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

}
