<?php if(count($especial) >0) :?>
<h3 class="title"><span>ESPECIAL</span></h3>
<div class="indexItems">
    <?php
    foreach ($especial as $anuncio) :
        /**
         * @var $sex \Anuncios\Entity\Sex
         */
        $sex = $anuncio;
        $image = $sex->getImages()->first();
        if (empty($image)) {
            $url = '';
        }else {
            $url = $sex->getImages()->first()->getUrl();
        }?>
    <div class="displayStyle">
        <div class="itemBlock">
            <span class="indexItemsImageMask"></span>
			<span class="itemBlockAction">
				<a class="aniBtn" href="<?php echo $this->url('anuncios', array('action' => 'index', 'category' => $sex->getCategory()->getId()));?>" ><i class="icon-search"></i></a>
				<a class="aniBtn" data-my-tooltip="tooltip" href="<?php echo $this->url('article', array('article' => $sex->getUrl())); ?>" data-original-title="Details"><i class="icon-link"></i></a>
			</span>
            <a href="#" class="indexProductsImage">
                <img src="<?php echo $this->page()->getUrl('image',$url);?>" alt="<?php echo $sex->getTitle();?>" title="<?php echo $sex->getTitle();?>">
            </a>
        </div>
    </div>
    <?php endforeach;?>
</div>
<?php endif;?>