<?php
/**
* @var $sex \Anuncios\Entity\Sex
*/
?>
<section id="mainBody">
<div class="container">
<h3 class="title"><span>INFORMAÇÕES</span></h3>
<div class="row">
    <div class="span6">
        <div id="detailViewCarousel" class="carousel slide">
            <div class="displayStyle">
                <ol class="carousel-indicators">
                    <?php $i=0;?>
                    <?php if(count($sex->getImages()) > 0) :?>
                    <?php foreach($sex->getImages() as $image) : ?>
                        <li data-target="#detailViewCarousel" data-slide-to="<?php echo $i;?>" class="<?php echo $i==0 ? 'active' : '';?>"></li>
                    <?php $i++; endforeach;?>
                    <?php else :?>
                        <li data-target="#detailViewCarousel" data-slide-to="<?php echo $i;?>" class="<?php echo $i==0 ? 'active' : '';?>"></li>
                    <?php endif;?>
                </ol>
                <!-- Carousel items -->
                <div class="carousel-inner">
                    <?php $i=0;?>
                    <?php if(count($sex->getImages()) > 0) :?>
                    <?php foreach($sex->getImages() as $image) :
                        $url = $image->getUrl();
                        if(empty($url)) {
                            $url = '';
                        } ?>
                        <div class="<?php echo $i==0 ? 'active' : '';?> item"><img src="<?php echo $this->page()->getUrl('image', $url); ?>" alt="<?php $sex->getTitle() . 'image' . $i;?>" /></div>
                    <?php $i++; endforeach;?>
                    <?php else :?>
                        <div class="<?php echo $i==0 ? 'active' : '';?> item"><img src="<?php echo $this->page()->getUrl('image', ''); ?>" alt="<?php $sex->getTitle() . 'image' . $i;?>" /></div>
                    <?php endif;?>
                </div>
                <!-- Carousel nav -->
                <a class="carousel-control left" href="#detailViewCarousel" data-slide="prev">&lsaquo;</a>
                <a class="carousel-control right" href="#detailViewCarousel" data-slide="next">&rsaquo;</a>
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="promoDetail">
            <h1><?php echo $sex->getTitle(); ?></h1>
            <p>Detalhes</p>
            <ul>
                <li>Cidade : <a href="<?php echo $this->url('anuncios', array('action' => 'index', 'city' => $sex->getCity()->getId()));?>"><?php echo $sex->getCity()->getName();?></a></li>
                <li>Local : <?php echo $sex->getLocal()?></li>
                <li>Categoria : <a href="<?php echo $this->url('anuncios', array('action' => 'index', 'category' => $sex->getCategory()->getId()));?>"><?php echo $sex->getCategory()->getName();?></a></li>
                <li>Publicado em : <?php echo $this->page()->formatDate($sex->getCreated());?></li>
                <?php if($sex->getCreated()->getTimestamp() !== $sex->getUpaded()->getTimestamp() ) { ?>
                <li>Actualizado em : <?php echo $this->page()->formatDate($sex->getCreated());?></li>
                <?php }?>
                <li>Expira em : <?php echo $this->page()->formatDate($sex->getExpiration());?></li>
            </ul>
            <?php if($sex->getSendemail() != 'NO'):?>
                <p>Responder para: <a href="mailto:<?php echo $sex->getEmail();?>"><?php echo $sex->getEmail();?></a></p>
            <?php endif;?>
            <br>
        </div>
        <br>
        <div class="span6">
            <strong>Sobre Mim</strong>
                <p><?php echo $this->page()->getDescription($sex->getDescription(), 5000);?></p>
        </div>
    </div>
</div>
<div class="row">
    <?php if(count($nDestaques) >=  1) :?>
    <section id="featuredProduct">
        <h3 class="title"><span>Anúncios em destaque</span></h3>
        <div id="myCarouselOne" class="carousel slide">
            <!-- Dot Indicators -->
            <div class="carousel-inner">
                <?php echo $this->partial('application/partial/row',['nDestaques' => $nDestaques, 'lines' => $lines]);?>
            </div>
            <a class="left carousel-control" href="#myCarouselOne" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarouselOne" data-slide="next">›</a>
        </div>
        <?php endif;?>
</div>
</section>