<?php
/**
 * @var $sex \Anuncios\Entity\Sex
 */
$sex = $anuncio;
$image = $sex->getImages()->first();
if(empty($image)) {
    $url = '';
}else {
    $url = $sex->getImages()->first()->getUrl();
}
?>
<li class="span3">
    <div class="thumbnail">
        <img src="<?php echo $this->page()->getUrl('image', $url); ?>" alt="<?php echo $sex->getCategory()->getName(); ?>">
        <div class="caption">
            <h3><?php echo $sex->getTitle(); ?></h3>
            <p class="detailNprice">
                <span><?php echo strtoupper($this->page()->getDescription($sex->getDescription())); ?></span>
            </p>
            <p>
                <?php if($sex->getSendemail() != 'NO'):?>
                    <a class="btn btn-warning" href="mailto:<?php echo $sex->getEmail();?>">contactar <i class="icon-comment"></i></a>
                <?php endif;?>
                <a class="btn" href="<?php echo $this->url('article', array('article' => $sex->getUrl())); ?>">ver informação</a>
            </p>
        </div>
        <div class="cntr">
            <p class="badge badge-inverse"><?php echo $this->page()->formatDate($sex->getUpaded());?></p>
        </div>
    </div>
</li>