<?php if(count($listOfSexs) > 0) :?>
<h3 class="title"><span><?php echo $title;?></span></h3>
<ul class="thumbnails">
    <?php foreach ($this->paginator as $anuncio) {
        echo $this->partial('partial/article/generic', ['anuncio' => $anuncio]);
    } ?>
</ul>
<div class="cntr">
    <?php
    if($type && count($this->paginator) > 1) {
        echo $this->paginationControl($this->paginator,
            'Sliding', // All, Elastic, Jumping, Sliding
            'partial/search_pagination', array('route' => 'paginator-doctrine', 'type' =>$type));
    }
    ?>
</div>
<?php else :?>
    <?php echo 'Não existem resultados'; ?>
<?php endif;?>