<h3 class="title"><span>Most selling Women's Clothing</span></h3>
<ul class="thumbnails">
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware3.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware1.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware4.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware5.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware2.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware6.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
</ul>
<div class="cntr"><a class="btn" href="#">view more <i class="icon-repeat"></i></a><br><hr class="soften"></div>