<section id="featuredProduct">
    <h3 class="title"><span>Em destaque</span></h3>
    <div id="showCase" class="row">
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            ver informação</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>