<section id="mainBody">
    <div class="container">
        <?php echo $this->partial('partial/breadcrumb', array('title' => 'Ajuda/FAQ', 'subtitle' =>
            'Ajuda/FAQ')); ?>
        <div class="row">
            <blockquote class="style-3">
                <h4>O sexoja.com é grátis?</h4>Sim. O sexoja é um serviço gratuito de publicação de anúncios de cariz adulto.
                    A única situação em que algum pagamento é feito surge apenas para anúncios em destaque
            </blockquote>
            <blockquote class="style-3">
                <h4>Quantos anúncios posso colocar?</h4>
                Pode colocar o numero de anuncios que quisser.</blockquote>
            <blockquote class="style-3"><h4>Acabei de colocar o meu anúncio mas não o vejo!</h4>
                Em norma o seu anúncio é aprovado de imediato, sem tempos de espera.
                No entanto se o seu anúncio contiver endereços de blogues ou outras páginas de internet é de imediato
                bloqueado.
            </blockquote>
            <blockquote class="style-3">
                <h4>Durante quantos dias o meu anúncio ficará online?</h4>
                O seu anúncio ficará online durante 30 dias, caso não o apague antes.
            </blockquote>
            <blockquote class="style-3"><h4>Preciso de editar ou apagar o anúncio, como faço?</h4>
                No sexoja.com facilitamos a sua vida, mas temos logins nem senhas.
                Se criou o anuncio sem estar logado basta criar uma conta com o email em que publicou o anuncio.
                Depois aceder a sua conta e editar ou apagar o que tem para apagar.
            </blockquote>

            <blockquote class="style-3">
                <h4>Alguém copiou as minhas fotos, o que posso fazer?</h4>
                Primeiro terá que nos provar que as fotos são da sua autoria.
                Contacte-nos, depois de comprovarmos que as fotos são suas eliminaremos o anúncio da
                pessoa em questão. Se a mesma pessoa voltar a copiar as fotos, o seu IP será banido.
            </blockquote>

            <blockquote class="style-3"><h4>Vi um anúncio com detalhes e fotos falsas, o que posso fazer?</h4>
                Infelizmente nada podemos fazer, o que certamente acontecerá é essa pessoa perder contactos
                pela sua falsidade. O crime não compensa.
            </blockquote>
            <blockquote class="style-3"><h4>Alguém usou meus dados e imagem de forma ilegal, que posso fazer?</h4>
                Contacte-nos urgentemente, o anúncio será suspenso e caso haja autoridades policiais
                ao corrente da situação daremos todos os dados disponíveis nos nossos servidores.
                Este é um meio adulto e não para crianças.
            </blockquote>
            <blockquote class="style-3">
                <h4>Quais os limites de upload de imagens por cada anúncio?</h4>
                Pode colocar quatro imagens por cada anúncio, sendo que cada uma não pode exceder os 1000kb (1MB).
                Os formatos permitidos são: gif, jpg e png.
            </blockquote>

            <blockquote class="style-3">
                <h4>Quero publicitar o meu anúncio ou a minha página de uma forma destacada?</h4>
                Além dos tradicionais Anúncios em Destaque podemos colaborar com outro
                formato de anúncio. Contacte-nos e envie-nos a sua proposta para: contacto.sexoja@gmail.com
            </blockquote>

            <blockquote class="style-3"><h4>Dicas para ter sucesso com seu anúncio</h4>
                Deixamos aqui algumas dicas e sugestões para rentabilizar ao máximo o seu trabalho na
                área de anúncios online: <ul><li>Não abuse no número de anúncios, dá a ideia que
                        você está desesperado (a).</li>
                    <li>Não escreva com erros ortográficos ou
                        apenas maiúsculas, qualquer homem ou mulher gosta de pessoas
                        inteligentes, isto só dá uma má imagem sua.</li><li>Coloque sempre os seus dados e
                        fotos reais, porque mais vale ter um pássaro na mão do que dois a voar. Cliente não enganado voltará novamente.</li><li>Dê o maior número de detalhes possível, incluindo preços. Você gosta de ir a uma loja e os produtos não terem preço? Então porque não facilitar para os outros?</li><li>Invista nos nossos anúncios em destaque, sem investimento não há retorno.</li></ul></blockquote>

        </div>
    </div><!-- /container -->
</section>