<section id="mainBody">
<div class="container">
<div class="row">
<div id="sideBar" class="span3">

    <h3 class="title"><span>CART [ 2 ] </span></h3>
    <div class="row-fluid cartItem">
        <div class="span4"><a href="products.php"><img src="themes/images/clothes/1.jpg" alt="#"></a></div>
        <div class="span7"><h5> Women's Wear </h5><span>Qty. 1</span><br><span>Price:$12.00</span></div>
        <a class="close span1" data-dismiss="alert" href="#">&times;</a>
    </div>
    <div class="row-fluid cartItem">
        <div class="span4"><a href="products.php"><img src="themes/images/clothes/2.jpg" alt="#"></a></div>
        <div class="span7"><h5> Women's Wear </h5><span>Qty. 1</span><br><span>Price:$8.00</span></div>
        <a class="close span1" data-dismiss="alert" href="#">&times;</a>
    </div>

    <a class="btn btn-warning btn-large btn-block" href="checkout.php">Check out [ Total: $20.00 ]</a>

    <h3 class="title"><span>QUICK MENU  </span></h3>
    <div>
        <a class="btn btn-block" href="products.php">Women's Clothing (45)</a>
        <a class="btn btn-block" href="products.php">Women's Shoes (8)</a>
        <a class="btn btn-block" href="products.php">Women's Hand Bags (5)</a>
        <a class="btn btn-block" href="products.php">Men's Clothings  (45)</a>
        <a class="btn btn-block" href="products.php">Men's Shoes  (20)</a>
        <a class="btn btn-block" href="products.php">Kids Clothing (5)</a>
        <a class="btn btn-block" href="products.php">Kids Shoes (3)</a>
    </div>
    <h3 class="title"><span>SPECIAL </span></h3>
    <div class="indexItems">
        <div class=" displayStyle">
            <div class="itemBlock">
                <span class="indexItemsImageMask"></span>
			<span class="itemBlockAction">
				<a class="aniBtn" href="#" ><i class="icon-search"></i></a>
				<a class="aniBtn" data-my-tooltip="tooltip" href="details.php" data-original-title="Details"><i class="icon-link"></i></a>
			</span>
                <a href="#" class="indexProductsImage">
                    <img src="themes/images/clothes/special-women-ware.jpg" alt="Women's Clothing" title=" Women's Clothing ">
                </a>
            </div>
        </div>
    </div>

    <h3 class="title"><span>New  </span></h3>
    <div id="newCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="item">
                <div class="well">
                    <a class="displayStyle" href="#"><img src="themes/images/clothes/1.jpg" alt="#"/></a>
                    <h5>Clothings</h5>
                    <p>
                        <a class="btn btn-warning" href="#" > Add to <i class="icon-shopping-cart"></i></a>
                        <a class="btn" href="details.php">view details</a>
                    </p>
                    <p><span class="price"><small>$</small>400.00</span></p>
                </div>
            </div>
            <div class="item active">
                <div class="well">
                    <a class="displayStyle" href="#"><img src="themes/images/clothes/1.jpg" alt="#"/></a>
                    <h5>Clothings</h5>
                    <p>
                        <a class="btn btn-warning" href="#" > Add to <i class="icon-shopping-cart"></i></a>
                        <a class="btn" href="details.php">view details</a>
                    </p>
                    <p><span class="price"><small>$</small>400.00</span></p>
                </div>
            </div>
            <div class="item">
                <div class="well">
                    <a class="displayStyle" href="#"><img src="themes/images/clothes/1.jpg" alt="#"/></a>
                    <h5>Clothings</h5>
                    <p>
                        <a class="btn btn-warning" href="#" > Add to <i class="icon-shopping-cart"></i></a>
                        <a class="btn" href="details.php">view details</a>
                    </p>
                    <p><span class="price"><small>$</small>400.00</span></p>
                </div>
            </div>
            <div class="item">
                <div class="well">
                    <a class="displayStyle" href="#"><img src="themes/images/clothes/1.jpg" alt="#"/></a>
                    <h5>Clothings</h5>
                    <p>
                        <a class="btn btn-warning" href="#" > Add to <i class="icon-shopping-cart"></i></a>
                        <a class="btn" href="details.php">view details</a>
                    </p>
                    <p><span class="price"><small>$</small>400.00</span></p>
                </div>
            </div>
            <div class="item">
                <div class="well">
                    <a class="displayStyle" href="#"><img src="themes/images/clothes/1.jpg" alt="#"/></a>
                    <h5>Clothings</h5>
                    <p>
                        <a class="btn btn-warning" href="#" > Add to <i class="icon-shopping-cart"></i></a>
                        <a class="btn" href="details.php">view details</a>
                    </p>
                    <p><span class="price"><small>$</small>400.00</span></p>
                </div>
            </div>
            <div class="item">
                <div class="well">
                    <a class="displayStyle" href="#"><img src="themes/images/clothes/1.jpg" alt="#"/></a>
                    <h5>Clothings</h5>
                    <p>
                        <a class="btn btn-warning" href="#" > Add to <i class="icon-shopping-cart"></i></a>
                        <a class="btn" href="details.php">view details</a>
                    </p>
                    <p><span class="price"><small>$</small>400.00</span></p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#newCarousel" data-slide="prev">‹</a>
        <a class="right carousel-control" href="#newCarousel" data-slide="next">›</a>
    </div>

    <h3 class="title"><span>POPULAR </span></h3>
    <ul class="thumbnails">
        <li class="span3">
            <div class="thumbnail">
                <img src="themes/images/clothes/2.jpg" alt="#">
                <div class="caption">
                    <p>
                        <a href="details.php">view details</a>
                    </p>
                </div>
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail">
                <img src="themes/images/clothes/6.jpg" alt="#">
                <div class="caption">
                    <p>
                        <a href="details.php">view details</a>
                    </p>
                </div>
            </div>
        </li>
    </ul>
    <h3 class="title"><span>FEATURED </span></h3>
    <ul class="media-list">
        <li class="media">
            <a class="pull-left" href="#"><img src="themes/images/clothes/2.jpg" alt="Women's Clothing" title=" Women's Clothing " ></a>
            <div class="media-body">
                <h4 class="media-heading"><a href="#">Women's Clothing</a></h4>
                <span>$14.00</span>
            </div>
        </li>
        <li class="media">
            <a class="pull-left" href="#"><img src="themes/images/clothes/3.jpg" alt="Women's Clothing" title=" Women's Clothing "></a>
            <div class="media-body">
                <h4 class="media-heading"><a href="#">Women's Clothing</a></h4>
                <span class="normalprice">$18.00 </span>&nbsp;<span class="specialPrice">$9.00</span>
                <span class="discount"><br>Save:&nbsp;50% off</span>
            </div>
        </li>
    </ul>

</div>

<div class="span9">
<div class="products">
<h3 class="title"><span>Women's Clothing</span></h3>
<div class="row">
    <div class="span3">
        <div class="indexItems">
            <div class="indexItems">
                <div class=" displayStyle">
                    <div class="itemBlock">
                        <span class="indexItemsImageMask"></span>
			<span class="itemBlockAction">
				<a class="aniBtn" href="#" ><i class="icon-search"></i></a>
				<a class="aniBtn" data-my-tooltip="tooltip" href="details.php" data-original-title="Details"><i class="icon-link"></i></a>
			</span>
                        <a href="#" class="indexProductsImage">
                            <img src="themes/images/clothes/special-women-ware.jpg" alt="Women's Clothing" title=" Women's Clothing ">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span3">
        <div class="indexItems">
            <div class="indexItems">
                <div class=" displayStyle">
                    <div class="itemBlock">
                        <span class="indexItemsImageMask"></span>
			<span class="itemBlockAction">
				<a class="aniBtn" href="#" ><i class="icon-search"></i></a>
				<a class="aniBtn" data-my-tooltip="tooltip" href="details.php" data-original-title="Details"><i class="icon-link"></i></a>
			</span>
                        <a href="#" class="indexProductsImage">
                            <img src="themes/images/clothes/special-women-ware.jpg" alt="Women's Clothing" title=" Women's Clothing ">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span3">
        <div class="indexItems">
            <div class="indexItems">
                <div class=" displayStyle">
                    <div class="itemBlock">
                        <span class="indexItemsImageMask"></span>
			<span class="itemBlockAction">
				<a class="aniBtn" href="#" ><i class="icon-search"></i></a>
				<a class="aniBtn" data-my-tooltip="tooltip" href="details.php" data-original-title="Details"><i class="icon-link"></i></a>
			</span>
                        <a href="#" class="indexProductsImage">
                            <img src="themes/images/clothes/special-women-ware.jpg" alt="Women's Clothing" title=" Women's Clothing ">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<h3 class="title"><span>Most selling Women's Clothing</span></h3>
<ul class="thumbnails">
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware3.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware1.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware4.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware5.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware2.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/women/bootstrap-women-ware6.jpg" alt="#">
            <div class="caption">
                <h3>Women's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
</ul>
<div class="cntr"><a class="btn" href="#">view more <i class="icon-repeat"></i></a><br><hr class="soften"></div>

<h3 class="title"><span>Kids Wear</span></h3>
<ul class="thumbnails">
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/kids/bootstrap-kids-ware1.png" alt="#">
            <div class="caption">
                <h3>Kids Wear</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/kids/bootstrap-kids-ware2.png" alt="#">
            <div class="caption">
                <h3>Kids Wear</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/kids/bootstrap-kids-ware3.png" alt="#">
            <div class="caption">
                <h3>Kids Wear</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/kids/bootstrap-kids-ware4.png" alt="#">
            <div class="caption">
                <h3>Kids Wear</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/kids/bootstrap-kids-ware5.png" alt="#">
            <div class="caption">
                <h3>Kids Wear</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/kids/bootstrap-kids-ware6.png" alt="#">
            <div class="caption">
                <h3>Kids Wear</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
</ul>

<div class="cntr"><a class="btn" href="#">view more <i class="icon-repeat"></i></a><br><hr class="soften"></div>

<h3 class="title"><span>Men's Clothing</span></h3>
<ul class="thumbnails">
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/a3.jpg" alt="#">
            <div class="caption">
                <h3>Men's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img src="themes/images/clothes/a6.jpg" alt="#">
            <div class="caption">
                <h3>Men's Clothing</h3>
                <p class="detailNprice">
                    <small class="oldPrice">&nbsp;</small>$<span>8.00</span>
                </p>
                <p>
                    <a class="btn btn-warning" href="#"> Add to <i class="icon-shopping-cart"></i></a>
                    <a class="btn" href="details.php">view details</a>
                </p>
            </div>
        </div>
    </li>

</ul>
</div>
</div>
</div>

<!-- ======================================================================================================================== -->
<!-- ======================================================================================================================== -->
<section id="featuredProduct">
    <h3 class="title"><span>Related Products</span></h3>
    <div id="showCase" class="row">
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="span2">
            <div class="carousel slide">
                <div class="carousel-inner">
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma1.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma6.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma5.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item active left">
                        <a href="details.php"><img src="themes/images/clothes/sma4.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item next left">
                        <a href="details.php"><img src="themes/images/clothes/sma3.jpg" alt="#">
                            View Details</a>
                    </div>
                    <div class="item">
                        <a href="details.php"><img src="themes/images/clothes/sma2.jpg" alt="#">
                            View Details</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</div>
</section>