<section id="mainBody">
    <div class="container">
        <?php echo $this->partial('partial/breadcrumb', array('title' => 'Publicidade Banners',
            'subtitle' =>
            'Publicidade Banners')); ?>
        <div class="row">
            <p>
                Ao ter um banner na nossa primeira pagina, pode fazer com que o site da sua empresa ou do seu serviço seja muitas vezes visitado.
            </p>
        <div class="content-main-title">
            <h2 class="font-replace">Como publicar o seu banner?</h2>
        </div>
        <div class="article-main-content">
            <p>1) Para conseguir ver o seu banner em destaque no rodápe da primeira pagina basta entrar em contacto com a nossa equipa <a href="mailto:contacto.sexoja@gmail.com">contacto.sexoja@gmail.com</a></p>
            <p>2) Enviar o banner que pretende á vossa equipa, sendo que as dimesões tem de ser de 120 × 45 pixels e claro tem de dizer o tempo que pretende o banner!</p>
            <p>3) Depois do seu do seu pagamento o seu banner é publicado com para a imagem e com o respectivo link do vosso site que nos foi fornecido.</p>
            <p>Os prazos e valores de pagamento disponíveis são os seguintes:</p>
            <ul>
                <li>Durante 30 dias - Valor: 30 €</li>
                <li>Durante 60 dias - Valor: 40€</li>
                <li>Durante 90 dias - Valor: 50€</li>
            </ul>
            <p>O único método de pagamento disponível é a transferência bancária. </p>
            <p>Caso surjam dúvidas ou problemas estamos sempre disponíveis via email:
                <a href="mailto:contacto.sexoja@gmail.com">contacto.sexoja@gmail.com</a></p>
        </div>
        </div>
    </div><!-- /container -->
</section>