<section id="mainBody">
    <div class="container">
        <?php echo $this->partial('partial/breadcrumb', array('title' => 'Publicidade Banners',
            'subtitle' =>
            'Publicidade Banners')); ?>
        <div class="row">
            <p>
                Ao ter um banner na nossa primeira pagina, pode fazer com que o site da sua empresa ou do seu serviço seja muitas vezes visitado.
            </p>
        <div class="content-main-title">
            <h2 class="font-replace">Como publicar o seu banner?</h2>
        </div>
        <div class="article-main-content">
            <p>1) Para conseguir ver o seu banner em destaque no rodápe da primeira pagina é necessario efectuar um simples registo no site, se mais tarde quisser gerir o banner - senao posteriormente cria um registo com o mesmo email que criou o banner.</p>
            <p>2) Comece por publicar o seu banner , clicando no botão normal "PUBLICAR BANNER NO RODAPE" que és no top da pagina. </p>
            <p>3) Depois do seu banner estar publicado e aprovado pela nossa equipa aṕos confirmacao de pagamento.</p>
            <p>Os prazos e valores de pagamento disponíveis são os seguintes:</p>
            <ul>
                <li>Durante 7 dias - Valor: 5€</li>
                <li>Durante 15 dias - Valor: 10€</li>
                <li>Durante 30 dias - Valor: 15€</li>
            </ul>
            <p>O único método de pagamento disponível é a transferência bancária. </p>
            <p>Caso surjam dúvidas ou problemas estamos sempre disponíveis via email:
                <a href="mailto:contacto.sexoja@gmail.com">contacto.sexoja@gmail.com</a></p>
        </div>
        </div>
    </div><!-- /container -->
</section>