<section id="mainBody">
    <div class="container">
        <?php echo $this->partial('partial/breadcrumb', array('title' => 'Anuncio em destaque',
            'subtitle' =>
                'Anuncio em destaque')); ?>
        <div class="row">
            <p>
                Ao ter um anuncio em destaque no nosso portal tem muitas vantagens. Mais visitas, mais clientes e mais telefomenas.
            </p>
            <div class="content-main-title">
                <h2 class="font-replace">Como publicar o seu anuncio em destaque?</h2>
            </div>
            <div class="article-main-content">
                <p>1) Existem 2 tipos de destaque, anuncio grande na primeira pagina, e o destaque mais pequeno tambem na primeira pagina. Na listagem de anuncios os destaques aparecem tambem nessa pagina.</p>
                <p>2) Comece por publicar o seu anuncio , clicando no botão normal "ANUNCIAR" que és no top da pagina. </p>
                <p>3) Depois do seu anuncio estar publicado e aprovado pela nossa equipa aṕos confirmacao de pagamento ele aparece na pagina. Pode ser criar um registo para gerir os seus anuncios</p>
                <p>Os prazos e valores de pagamento disponíveis são os seguintes:</p>
                <h3>ANUNCIO COM GRANDE DESTAQUE NA PRIMEIRA PAGINA</h3>
                <ul>
                    <li>Durante 7 dias - Valor: 5€</li>
                    <li>Durante 15 dias - Valor: 10€</li>
                    <li>Durante 30 dias - Valor: 15€</li>
                </ul>
                <h3>ANUNCIO PEQUENO DESTAQUE NA PRIMEIRA PAGINA</h3>
                <ul>
                    <li>Durante 7 dias - Valor: 3€</li>
                    <li>Durante 15 dias - Valor: 6€</li>
                    <li>Durante 30 dias - Valor: 9€</li>
                </ul>
                <p>O único método de pagamento disponível é a transferência bancária.</p>
                <p>Caso surjam dúvidas ou problemas estamos sempre disponíveis via email:
                    <a href="mailto:contacto.sexoja@gmail.com">contacto.sexoja@gmail.com</a></p>
            </div>
        </div>
    </div><!-- /container -->
</section>