<?php if(count($top) >= 3) : ?>
<section id="mainCarousel">
    <div class="displayStyle">
        <div id="myCarousel" class="carousel slide">
            <span class="tagRight"></span>
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <?php echo $this->partial('application/partial/big_row',['top' => $top]);?>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
        </div>
    </div>
</section>
<?php endif;?>
<?php if(count($nDestaques)== 2 && count($nDestaques[0])==4 && count($nDestaques[1])==4) :?>
<section id="featuredProduct">
<h3 class="title"><span>Anúncios em destaque</span></h3>
<div id="myCarouselOne" class="carousel slide">
    <!-- Dot Indicators -->
    <div class="carousel-inner">
        <?php echo $this->partial('application/partial/row',['nDestaques' => $nDestaques, 'lines' => $lines]);?>
    </div>
    <a class="left carousel-control" href="#myCarouselOne" data-slide="prev">‹</a>
    <a class="right carousel-control" href="#myCarouselOne" data-slide="next">›</a>
</div>
<?php endif;?>
</section>
<section id="scn">
    <h3 class="title"><span>Sobre nos</span></h3>
    <div class="row">
        <div class="span4">
            <h1><i class="icon-heart"></i> </h1>
            <h4>Porque?</h4>
            <p>Muitos sao os dias que precisamos de amor, carinho e afeto. Os servicos profissionais estao aqui para o ajudar. Os nossos anuncios primam pela qualidade e privacidade. Satisfaca o seu prazer... E fique tranquilizado.</p>
            <p>Este portal tambem se destina a todos os outros interessados em encontros sem qualquer  compromisso ou custo. Solteira ou casada e solteiro ou casado. Marcar um encontro, nunca foi tao facil. No SexoJa.com é possivel juntar o prazer de um bom encontro a um final feliz. Tudo á distancia de um clique.
            </p>
        </div>
        <div class="span4">
            <div class="seperator">
                <h1><i class="icon-truck iconShipping"></i> </h1>
                <h4>Um encontro saudavel</h4>
                <p>Um encontro saudavel é o resultado de uma relacão protegida. O resultado sera sempre bom pois ambos definem o horizonte. Nao tenha medo, nos estamos aqui para o ajudar a acabar com os seus momentos de solidao. Qualidade e a nossa receita. Por isso clique em anunciar, e amanha sera voce a pegar no carro ou apanhar o transporte publico para a melhor noite da sua vida.</p>

            </div>
        </div>
        <div class="span4">
            <h1><i class="icon-comments-alt"></i> </h1>
            <h4>Encontre-nos e faça um gosto</h4>
            <p class="findUs">
                <a target="_blank" href="https://www.facebook.com/pages/sexojacom/589694244484300"><i class="icon-facebook"></i></a>
            </p>
            <h4>Publique ja o seu anuncio gratuitamente</h4>
            <div class="caption">
                    <div class="control-group">
                        <div class="controls">
                            <a href="<?php echo $this->url('anunciar', array('action' => 'add'));?>" class="btn btn-success ">PUBLICAR UM ANUNCIO</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</section>
<hr class="soften"/>
<?php echo $this->partial('application/partial/marcas', ['marcas' => $marcas]);?>
