<?php if(count($top) >= 3) : ?>
<section id="mainCarousel">
    <div class="displayStyle">
        <div id="myCarousel" class="carousel slide">
            <span class="tagRight"></span>
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <?php echo $this->partial('application/partial/big_row',['top' => $top]);?>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
        </div>
    </div>
</section>
<?php endif;?>
<?php if(count($nDestaques)== 2 && count($nDestaques[0])==4 && count($nDestaques[1])==4) :?>
<section id="featuredProduct">
<h3 class="title"><span>Anúncios em destaque</span></h3>
<div id="myCarouselOne" class="carousel slide">
    <!-- Dot Indicators -->
    <div class="carousel-inner">
        <?php echo $this->partial('application/partial/row',['nDestaques' => $nDestaques, 'lines' => $lines]);?>
    </div>
    <a class="left carousel-control" href="#myCarouselOne" data-slide="prev">‹</a>
    <a class="right carousel-control" href="#myCarouselOne" data-slide="next">›</a>
</div>
<?php endif;?>
</section>
<section id="scn">
    <h3 class="title"><span>Sobre nos</span></h3>
    <div class="row">
        <div class="span4">
            <h1><i class="icon-heart"></i> </h1>
            <h4>Porque?</h4>
            <p>Muitas das vezes, precisamos de amor carinho e afecto. Estar com uma "profissional" não quer dizer que vamos correr risco, muito pelo contrario vamos satisfazer o nosso prazer... E ficar tranquilizados.</p>
            <p>Este portal tambem se destina aos solteiros e solteiras que podem colocar aqui os seus anuncios e marcar encontros sem qualquer custo, marcar um café, um passeio entre outros. Apensas serve para juntar o ultil ao agradável...</p>
        </div>
        <div class="span4">
            <div class="seperator">
                <h1><i class="icon-truck iconShipping"></i> </h1>
                <h4>Um encontro saudavel</h4>
                <p>Um encontro saudavel estar em ter uma relacão protegida. Sera bom para si e para quem o acompanha independentemente do seu cariz sexual. Mas nao tenha medo. Deixe os vicios de lado como mastrubacao e passe a fazer sexo saudavel mesmo que seja com uma acompanhe. Por isso pegue no carro ou apanhe os transportes publicos e desfrute de uma boa foda!</p>

            </div>
        </div>
        <div class="span4">
            <h1><i class="icon-comments-alt"></i> </h1>
            <h4>Encontre-nos e faça um gosto</h4>
            <p class="findUs">
                <a target="_blank" href="https://www.facebook.com/pages/sexojacom/589694244484300"><i class="icon-facebook"></i></a>
            </p>
            <h4>Publique ja o seu anuncio gratuitamente</h4>
            <div class="caption">
                    <div class="control-group">
                        <div class="controls">
                            <a href="<?php echo $this->url('anunciar', array('action' => 'add'));?>" class="btn btn-success ">PUBLICAR UM ANUNCIO</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</section>
<hr class="soften"/>
<?php echo $this->partial('application/partial/marcas', ['marcas' => $marcas]);?>
