<section id="mainBody">
    <div class="container">
        <?php echo $this->partial('partial/breadcrumb', array('title' => 'Termos e condições', 'subtitle' =>
                'Termos e condições')); ?>
        <div class="row">
            <div class="span12">
                <h3>Anuncios</h3>
                <p>O <span style="font-weight: bold;">sexoja.com</span> é uma publicação online de conteúdo erótico, destinada exclusivamente a pessoas maiores de 18 anos, que reconhecem que estão a aceder a conteúdo erótico e que concordam incondicionalmente com estes Termos e Condições.
                  Os Termos e Condições gerais deste site podem ser alterados a qualquer momento e sem qualquer aviso prévio.</p>
                <p>Somos apenas um portal de classificados para adultos e não uma agência.</p>
                <h5>1. Informações do Anúncio</h5>
                <p>Todas as informações que constam nos anúncios foram-nos fornecidas por preencimento via site e são da inteira responsabilidade dos anunciantes.
                O Anunciante compromete-se em fornecer informação verdadeira, concreta e actualizada, bem como a manter e actualizar os respectivos dados pessoais de registo.
                Disponibilizamos uma equipa de profissionais com experiência em fotografia erótica.</p>

                <h5>2. Denúncia de conteúdos</h5>
                <p>O <span style="font-weight: bold;">sexoja.com</span> apenas publica anúncios de pessoas com idade superior a 18 anos. Alguma suspeita em contrário agradecemos que nos informe para que possamos agir de acordo com a lei em vigor.
                O utilizador poderá proceder à denúncia de conteúdos através do e-mail <a href="mailto:contacto.sexoja@gmail.com">contacto.sexoja@gmail.com</a></p>

                <h5>3. Lei e Foro Aplicável</h5>
                <p>Todas as referências e dados pessoais publicados no website <span style="font-weight: bold;">sexoja.com</span> são controlados pela equipa responsável pelo website.
                Estes dados são de pessoas maiores de 18 anos cuja identidade foi comprovada por documento identificativo. Assinaram um Termo de Autorização e Responsabilidade, autorizando o sexoja.com a a publicar os seus anúncios,
                assumindo, desde já, todas as responsabilidades daí decorrentes. Reservamo-nos o direito de seleccionar o conteúdo a ser publicado.
                O <span style="font-weight: bold;">sexoja.com</span> está interdito a visitantes de países, regiões ou quaisquer outros
                    locais onde o conteúdo do <span style="font-weight: bold;">sexoja.com</span> não seja legal, sendo o acesso sempre da responsabilidade do visitante.</p>

                <h5>4. Apoio ao Cliente</h5>
                <p>Quaisquer esclarecimentos, dúvidas ou informações adicionais podem ser solicitados através do email:
                    <a href="mailto:contacto.sexoja@gmail.com">contacto.sexoja@gmail.com</a></p>

                <h5>5. Editar e remover anuncios</h5>
                <p>Edite ou apague o seu anúncio a qualquer momento para faze-lo basta registar-se com o mesmo email de
                publicaçao do anuncio.!.</p>
               <h5>Outros...</h5>
               <p>♥ Se corretamente preenchido, o seu anúncio estará online durante 30 dias e visível diariamente.</p>
            </div>
        </div>
    </div><!-- /container -->
</section>